;; 
;; libBeresta
;; 
;; Заголовочные файлы для Embeddable Common Lisp (ecl)
;; Дмитрий Соломенников, (с) 2025-2026
;;

(in-package #:cl-beresta)

(include-header)

(pointer Error)

(enum ErrorKind (
   
  (ARRAY-COUNT-ERR #x1001) 
  (ARRAY-ITEM-NOT-FOUND #x1002) 
  (ARRAY-ITEM-UNEXPECTED-TYPE #x1003) 
  (BINARY-LENGTH-ERR #x1004) 
  (CANNOT-GET-PALETTE #x1005) 
  (DICT-COUNT-ERR #x1007) 
  (DICT-ITEM-NOT-FOUND #x1008) 
  (DICT-ITEM-UNEXPECTED-TYPE #x1009) 
  (DICT-STREAM-LENGTH-NOT-FOUND #x100A) 
  (DOC-ENCRYPTDICT-NOT-FOUND #x100B) 
  (DOC-INVALID-OBJECT #x100C) 
  (DUPLICATE-REGISTRATION #x100E) 
  (EXCEED-JWW-CODE-NUM-LIMIT #x100F) 
  (ENCRYPT-INVALID-PASSWORD #x1011) 
  (ERR-UNKNOWN-CLASS #x1013) 
  (EXCEED-GSTATE-LIMIT #x1014) 
  (FAILED-TO-ALLOC-MEM #x1015) 
  (FILE-IO-ERROR #x1016) 
  (FILE-OPEN-ERROR #x1017) 
  (FONT-EXISTS #x1019) 
  (FONT-INVALID-WIDTH-TABLE #x101A) 
  (INVALID-AFM-HEADER #x101B) 
  (INVALID-ANNOTATION #x101C) 
  (INVALID-BIT-PER-COMPONENT #x101E) 
  (INVALID-CHAR-MATRIX-DATA #x101F) 
  (INVALID-COLOR-SPACE #x1020) 
  (INVALID-COMPRESSION-MODE #x1021) 
  (INVALID-DATE-TIME #x1022) 
  (INVALID-DESTINATION #x1023) 
  (INVALID-DOCUMENT #x1025) 
  (INVALID-DOCUMENT-STATE #x1026) 
  (INVALID-ENCODER #x1027) 
  (INVALID-ENCODER-TYPE #x1028) 
  (INVALID-ENCODING-NAME #x102B) 
  (INVALID-ENCRYPT-KEY-LEN #x102C) 
  (INVALID-FONTDEF-DATA #x102D) 
  (INVALID-FONTDEF-TYPE #x102E) 
  (INVALID-FONT-NAME #x102F) 
  (INVALID-IMAGE #x1030) 
  (INVALID-JPEG-DATA #x1031) 
  (INVALID-N-DATA #x1032) 
  (INVALID-OBJECT #x1033) 
  (INVALID-OBJ-ID #x1034) 
  (INVALID-OPERATION #x1035) 
  (INVALID-OUTLINE #x1036) 
  (INVALID-PAGE #x1037) 
  (INVALID-PAGES #x1038) 
  (INVALID-PARAMETER #x1039) 
  (INVALID-PNG-IMAGE #x103B) 
  (INVALID-STREAM #x103C) 
  (MISSING-FILE-NAME-ENTRY #x103D) 
  (INVALID-TTC-FILE #x103F) 
  (INVALID-TTC-INDEX #x1040) 
  (INVALID-WX-DATA #x1041) 
  (ITEM-NOT-FOUND #x1042) 
  (LIBPNG-ERROR #x1043) 
  (NAME-INVALID-VALUE #x1044) 
  (NAME-OUT-OF-RANGE #x1045) 
  (PAGES-MISSING-KIDS-ENTRY #x1049) 
  (PAGE-CANNOT-FIND-OBJECT #x104A) 
  (PAGE-CANNOT-GET-ROOT-PAGES #x104B) 
  (PAGE-CANNOT-RESTORE-GSTATE #x104C) 
  (PAGE-CANNOT-SET-PARENT #x104D) 
  (PAGE-FONT-NOT-FOUND #x104E) 
  (PAGE-INVALID-FONT #x104F) 
  (PAGE-INVALID-FONT-SIZE #x1050) 
  (PAGE-INVALID-GMODE #x1051) 
  (PAGE-INVALID-INDEX #x1052) 
  (PAGE-INVALID-ROTATE-VALUE #x1053) 
  (PAGE-INVALID-SIZE #x1054) 
  (PAGE-INVALID-XOBJECT #x1055) 
  (PAGE-OUT-OF-RANGE #x1056) 
  (REAL-OUT-OF-RANGE #x1057) 
  (STREAM-EOF #x1058) 
  (STREAM-READLN-CONTINUE #x1059) 
  (STRING-OUT-OF-RANGE #x105B) 
  (THIS-FUNC-WAS-SKIPPED #x105C) 
  (TTF-CANNOT-EMBED-FONT #x105D) 
  (TTF-INVALID-CMAP #x105E) 
  (TTF-INVALID-FORMAT #x105F) 
  (TTF-MISSING-TABLE #x1060) 
  (UNSUPPORTED-FONT-TYPE #x1061) 
  (UNSUPPORTED-JPEG-FORMAT #x1063) 
  (UNSUPPORTED-TYPE1-FONT #x1064) 
  (XREF-COUNT-ERR #x1065) 
  (ZLIB-ERROR #x1066) 
  (INVALID-PAGE-INDEX #x1067) 
  (INVALID-URI #x1068) 
  (PAGE-LAYOUT-OUT-OF-RANGE #x1069) 
  (PAGE-MODE-OUT-OF-RANGE #x1070) 
  (PAGE-NUM-STYLE-OUT-OF-RANGE #x1071) 
  (ANNOT-INVALID-ICON #x1072) 
  (ANNOT-INVALID-BORDER-STYLE #x1073) 
  (PAGE-INVALID-DIRECTION #x1074) 
  (PAGE-INSUFFICIENT-SPACE #x1076) 
  (PAGE-INVALID-DISPLAY-TIME #x1077) 
  (PAGE-INVALID-TRANSITION-TIME #x1078) 
  (INVALID-PAGE-SLIDESHOW-TYPE #x1079) 
  (EXT-GSTATE-OUT-OF-RANGE #x1080) 
  (INVALID-EXT-GSTATE #x1081) 
  (EXT-GSTATE-READ-ONLY #x1082) 
  (INVALID-ICC-COMPONENT-NUM #x1085) 
  (PAGE-INVALID-BOUNDARY #x1086) 
  (INVALID-SHADING-TYPE #x1088)))

(func Error-Check 
     "BRST_Error_Check" 
      STATUS 
  ((error Error)))

(func Doc-Error-Code 
     "BRST_Doc_Error_Code" 
      STATUS 
  ((pdf Doc)))

(func Doc-Error-DetailCode 
     "BRST_Doc_Error_DetailCode" 
      STATUS 
  ((pdf Doc)))

(func Doc-Error-Reset 
     "BRST_Doc_Error_Reset" 
      void 
  ((pdf Doc)))

(func Doc-Error-SetHandler 
     "BRST_Doc_Error_SetHandler" 
      STATUS 
  ((pdf Doc)
   (user-error-fn Error-Handler)))
