;; 
;; libBeresta
;; 
;; Заголовочные файлы для Embeddable Common Lisp (ecl)
;; Дмитрий Соломенников, (с) 2025
;;
;; Текст лицензии см. в файле ЛИЦЕНЗИЯ в корне проекта
;;
(in-package #:cl-beresta)

(include-header)

(synonym Page Dict)

(enum PageLayout (
  
  PAGE-LAYOUT-SINGLE
  PAGE-LAYOUT-ONE-COLUMN
  PAGE-LAYOUT-TWO-COLUMN-LEFT
  PAGE-LAYOUT-TWO-COLUMN-RIGHT
  PAGE-LAYOUT-TWO-PAGE-LEFT
  PAGE-LAYOUT-TWO-PAGE-RIGHT))

(enum PageMode (
  
  PAGE-MODE-USE-NONE
  PAGE-MODE-USE-OUTLINE
  PAGE-MODE-USE-THUMBS
  PAGE-MODE-FULL-SCREEN))

(enum PageNum (
  
  PAGE-NUM-DECIMAL
  PAGE-NUM-UPPER-ROMAN
  PAGE-NUM-LOWER-ROMAN
  PAGE-NUM-UPPER-LETTERS
  PAGE-NUM-LOWER-LETTERS))

(enum PageBoundary (
  
  PAGE-MEDIABOX
  PAGE-CROPBOX
  PAGE-BLEEDBOX
  PAGE-TRIMBOX
  PAGE-ARTBOX))

(enum PageTransition (
  
  PAGE-TRANSITION-WIPE-RIGHT
  PAGE-TRANSITION-WIPE-UP
  PAGE-TRANSITION-WIPE-LEFT
  PAGE-TRANSITION-WIPE-DOWN
  PAGE-TRANSITION-BARN-DOORS-HORIZONTAL-OUT
  PAGE-TRANSITION-BARN-DOORS-HORIZONTAL-IN
  PAGE-TRANSITION-BARN-DOORS-VERTICAL-OUT
  PAGE-TRANSITION-BARN-DOORS-VERTICAL-IN
  PAGE-TRANSITION-BOX-OUT
  PAGE-TRANSITION-BOX-IN
  PAGE-TRANSITION-BLINDS-HORIZONTAL
  PAGE-TRANSITION-BLINDS-VERTICAL
  PAGE-TRANSITION-DISSOLVE
  PAGE-TRANSITION-GLITTER-RIGHT
  PAGE-TRANSITION-GLITTER-DOWN
  PAGE-TRANSITION-GLITTER-TOP-LEFT-TO-BOTTOM-RIGHT
  PAGE-TRANSITION-REPLACE))

(enum PageOrientation (
  
  PAGE-ORIENTATION-PORTRAIT
  PAGE-ORIENTATION-LANDSCAPE))
