;; 
;; libBeresta
;; 
;; Заголовочные файлы для Embeddable Common Lisp (ecl)
;; Дмитрий Соломенников, (с) 2025
;;

(in-package #:cl-beresta)

(defctype Page Dict)

(defctype XObject Dict)

(defcenum PageLayout 
  :PAGE-LAYOUT-SINGLE
  :PAGE-LAYOUT-ONE-COLUMN
  :PAGE-LAYOUT-TWO-COLUMN-LEFT
  :PAGE-LAYOUT-TWO-COLUMN-RIGHT
  :PAGE-LAYOUT-TWO-PAGE-LEFT
  :PAGE-LAYOUT-TWO-PAGE-RIGHT
)

(defcenum PageMode 
  :PAGE-MODE-USE-NONE
  :PAGE-MODE-USE-OUTLINE
  :PAGE-MODE-USE-THUMBS
  :PAGE-MODE-FULL-SCREEN
)

(defcenum PageNum 
  :PAGE-NUM-DECIMAL
  :PAGE-NUM-UPPER-ROMAN
  :PAGE-NUM-LOWER-ROMAN
  :PAGE-NUM-UPPER-LETTERS
  :PAGE-NUM-LOWER-LETTERS
)

(defcenum PageBoundary 
  :PAGE-MEDIABOX
  :PAGE-CROPBOX
  :PAGE-BLEEDBOX
  :PAGE-TRIMBOX
  :PAGE-ARTBOX
)

(defcenum PageTransition 
  :PAGE-TRANSITION-WIPE-RIGHT
  :PAGE-TRANSITION-WIPE-UP
  :PAGE-TRANSITION-WIPE-LEFT
  :PAGE-TRANSITION-WIPE-DOWN
  :PAGE-TRANSITION-BARN-DOORS-HORIZONTAL-OUT
  :PAGE-TRANSITION-BARN-DOORS-HORIZONTAL-IN
  :PAGE-TRANSITION-BARN-DOORS-VERTICAL-OUT
  :PAGE-TRANSITION-BARN-DOORS-VERTICAL-IN
  :PAGE-TRANSITION-BOX-OUT
  :PAGE-TRANSITION-BOX-IN
  :PAGE-TRANSITION-BLINDS-HORIZONTAL
  :PAGE-TRANSITION-BLINDS-VERTICAL
  :PAGE-TRANSITION-DISSOLVE
  :PAGE-TRANSITION-GLITTER-RIGHT
  :PAGE-TRANSITION-GLITTER-DOWN
  :PAGE-TRANSITION-GLITTER-TOP-LEFT-TO-BOTTOM-RIGHT
  :PAGE-TRANSITION-REPLACE
)

(defcenum PageOrientation 
  :PAGE-ORIENTATION-PORTRAIT
  :PAGE-ORIENTATION-LANDSCAPE
)
