;; 
;; libBeresta
;; 
;; Заголовочные файлы для Embeddable Common Lisp (ecl)
;; Дмитрий Соломенников, (с) 2025
;;

(in-package #:cl-beresta)

(defcenum TextRenderingMode 
  :TEXT-RENDERING-MODE-FILL
  :TEXT-RENDERING-MODE-STROKE
  :TEXT-RENDERING-MODE-FILL-THEN-STROKE
  :TEXT-RENDERING-MODE-INVISIBLE
  :TEXT-RENDERING-MODE-FILL-CLIPPING
  :TEXT-RENDERING-MODE-STROKE-CLIPPING
  :TEXT-RENDERING-MODE-FILL-STROKE-CLIPPING
  :TEXT-RENDERING-MODE-CLIPPING
)

(defcenum TextAlignment 
  :TEXT-ALIGN-LEFT
  :TEXT-ALIGN-RIGHT
  :TEXT-ALIGN-CENTER
  :TEXT-ALIGN-JUSTIFY
)

(defcenum WritingMode 
  :WRITING-MODE-HORIZONTAL
  :WRITING-MODE-VERTICAL
)
