#ifndef BRST_ANNOTATION_H
#define BRST_ANNOTATION_H

// TODO дополнить определения аннотаций из стандарта
// TODO разложить определения по группам стандартов (1.2 -- 1.7)

#include "brst_types.h"
#include "brst_dict.h"
#include "brst_destination.h"

typedef enum _BRST_AnnotType {
    BRST_ANNOT_TEXT = 0,
    BRST_ANNOT_LINK,
    BRST_ANNOT_FREE_TEXT,
    BRST_ANNOT_LINE,
    BRST_ANNOT_SQUARE,
    BRST_ANNOT_CIRCLE,
    BRST_ANNOT_POLYGON,
    BRST_ANNOT_POLYLINE,
    BRST_ANNOT_HIGHLIGHT,
    BRST_ANNOT_UNDERLINE,
    BRST_ANNOT_SQUIGGLY,
    BRST_ANNOT_STRIKEOUT,
    BRST_ANNOT_STAMP,
    BRST_ANNOT_CARET,
    BRST_ANNOT_INK,
    BRST_ANNOT_POPUP,
    BRST_ANNOT_FILE_ATTACHMENT,
    BRST_ANNOT_SOUND,
    BRST_ANNOT_MOVIE,
    BRST_ANNOT_WIDGET,
    BRST_ANNOT_SCREEN,
    BRST_ANNOT_PRINTER_MARK,
    BRST_ANNOT_TRAPNET,
    BRST_ANNOT_WATERMARK,
    BRST_ANNOT_3D,
    BRST_ANNOT_REDACT,
    BRST_ANNOT_PROJECTION,
    BRST_ANNOT_RICH_MEDIA
} BRST_AnnotType;

typedef enum _BRST_AnnotFlags {
    BRST_ANNOT_FLAG_INVISIBLE,
    BRST_ANNOT_FLAG_HIDDEN,
    BRST_ANNOT_FLAG_PRINT,
    BRST_ANNOT_FLAG_NOZOOM,
    BRST_ANNOT_FLAG_NOROTATE,
    BRST_ANNOT_FLAG_NOVIEW,
    BRST_ANNOT_FLAG_READONLY,
    BRST_ANNOT_FLAG_LOCKED,
    BRST_ANNOT_FLAG_TOGGLE_NOVIEW,
    BRST_ANNOT_FLAG_LOCKED_CONTENT
} BRST_AnnotFlags;

typedef enum _BRST_AnnotHighlightMode {
    /// No highlighting.
    BRST_ANNOT_HIGHLIGHT_MODE_NONE = 0,
    /// Invert the contents of the annotation rectangle.
    BRST_ANNOT_HIGHLIGHT_MODE_INVERT,
    /// Invert annotation border.
    BRST_ANNOT_HIGHLIGHT_MODE_OUTLINE,
    /// Display the annotation as if it were being pushed below the surface of the page.
    BRST_ANNOT_HIGHLIGHT_MODE_PUSH
} BRST_AnnotHighlightMode;

/**
  Default types of annotation icon

  PDF book, table 172
*/
typedef enum _BRST_AnnotIcon {
    /// "Comment"
    BRST_ANNOT_ICON_COMMENT = 0,
    /// "Key"
    BRST_ANNOT_ICON_KEY,
    /// "Note"
    BRST_ANNOT_ICON_NOTE,
    /// "Help"
    BRST_ANNOT_ICON_HELP,
    /// "NewParagraph"
    BRST_ANNOT_ICON_NEW_PARAGRAPH,
    /// "Paragraph"
    BRST_ANNOT_ICON_PARAGRAPH,
    /// "Insert"
    BRST_ANNOT_ICON_INSERT,
    /// Last icon type at enumeration
    BRST_ANNOT_ICON_EOF
} BRST_AnnotIcon;

typedef enum _BRST_AnnotIntent {
    BRST_ANNOT_INTENT_FREETEXTCALLOUT = 0,
    BRST_ANNOT_INTENT_FREETEXTTYPEWRITER,
    BRST_ANNOT_INTENT_LINEARROW,
    BRST_ANNOT_INTENT_LINEDIMENSION,
    BRST_ANNOT_INTENT_POLYGONCLOUD,
    BRST_ANNOT_INTENT_POLYLINEDIMENSION,
    BRST_ANNOT_INTENT_POLYGONDIMENSION
} BRST_AnnotIntent;

typedef enum _BRST_AnnotLineCapPosition {
    BRST_ANNOT_LINE_CAP_INLINE = 0,
    BRST_ANNOT_LINE_CAP_TOP
} BRST_AnnotLineCapPosition;

typedef enum _BRST_AnnotLineEnd {
    BRST_ANNOT_LINE_END_NONE = 0,
    BRST_ANNOT_LINE_END_SQUARE,
    BRST_ANNOT_LINE_END_CIRCLE,
    BRST_ANNOT_LINE_END_DIAMOND,
    BRST_ANNOT_LINE_END_OPENARROW,
    BRST_ANNOT_LINE_END_CLOSEDARROW,
    BRST_ANNOT_LINE_END_BUTT,
    BRST_ANNOT_LINE_END_ROPENARROW,
    BRST_ANNOT_LINE_END_RCLOSEDARROW,
    BRST_ANNOT_LINE_END_SLASH
} BRST_AnnotLineEnd;

typedef enum _BRST_LineAnnotCapPosition {
    BRST_LINE_ANNOT_CAP_INLINE = 0,
    BRST_LINE_ANNOT_CAP_TOP
} BRST_LineAnnotCapPosition;

typedef enum _BRST_AnnotStampStyle {
    BRST_ANNOT_STAMP_APPROVED = 0,
    BRST_ANNOT_STAMP_EXPERIMENTAL,
    BRST_ANNOT_STAMP_NOTAPPROVED,
    BRST_ANNOT_STAMP_ASIS,
    BRST_ANNOT_STAMP_EXPIRED,
    BRST_ANNOT_STAMP_NOTFORPUBLICRELEASE,
    BRST_ANNOT_STAMP_CONFIDENTIAL,
    BRST_ANNOT_STAMP_FINAL,
    BRST_ANNOT_STAMP_SOLD,
    BRST_ANNOT_STAMP_DEPARTMENTAL,
    BRST_ANNOT_STAMP_FORCOMMENT,
    BRST_ANNOT_STAMP_TOPSECRET,
    BRST_ANNOT_STAMP_DRAFT,
    BRST_ANNOT_STAMP_FORPUBLICRELEASE
} BRST_AnnotStampStyle;

typedef BRST_Dict BRST_Annotation;

#endif /* BRST_ANNOTATION_H */
