#ifndef BRST_PAGE_H
#define BRST_PAGE_H

typedef BRST_Dict BRST_Page;
typedef BRST_Dict BRST_XObject;

typedef enum _BRST_PageLayout {
    BRST_PAGE_LAYOUT_SINGLE = 0,
    BRST_PAGE_LAYOUT_ONE_COLUMN,
    BRST_PAGE_LAYOUT_TWO_COLUMN_LEFT,
    BRST_PAGE_LAYOUT_TWO_COLUMN_RIGHT,
    BRST_PAGE_LAYOUT_TWO_PAGE_LEFT,
    BRST_PAGE_LAYOUT_TWO_PAGE_RIGHT,
    BRST_PAGE_LAYOUT_EOF
} BRST_PageLayout;

typedef enum _BRST_PageMode {
    BRST_PAGE_MODE_USE_NONE = 0,
    BRST_PAGE_MODE_USE_OUTLINE,
    BRST_PAGE_MODE_USE_THUMBS,
    BRST_PAGE_MODE_FULL_SCREEN,
/*  BRST_PAGE_MODE_USE_OC,
    BRST_PAGE_MODE_USE_ATTACHMENTS,
 */
    BRST_PAGE_MODE_EOF
} BRST_PageMode;

typedef enum _BRST_PageNum {
    BRST_PAGE_NUM_DECIMAL = 0,
    BRST_PAGE_NUM_UPPER_ROMAN,
    BRST_PAGE_NUM_LOWER_ROMAN,
    BRST_PAGE_NUM_UPPER_LETTERS,
    BRST_PAGE_NUM_LOWER_LETTERS,
    BRST_PAGE_NUM_EOF
} BRST_PageNumStyle;

/*----- slide show -----------------------------------------------------------*/

typedef enum _BRST_PageTransition {
    BRST_PAGE_TRANSITION_WIPE_RIGHT = 0,
    BRST_PAGE_TRANSITION_WIPE_UP,
    BRST_PAGE_TRANSITION_WIPE_LEFT,
    BRST_PAGE_TRANSITION_WIPE_DOWN,
    BRST_PAGE_TRANSITION_BARN_DOORS_HORIZONTAL_OUT,
    BRST_PAGE_TRANSITION_BARN_DOORS_HORIZONTAL_IN,
    BRST_PAGE_TRANSITION_BARN_DOORS_VERTICAL_OUT,
    BRST_PAGE_TRANSITION_BARN_DOORS_VERTICAL_IN,
    BRST_PAGE_TRANSITION_BOX_OUT,
    BRST_PAGE_TRANSITION_BOX_IN,
    BRST_PAGE_TRANSITION_BLINDS_HORIZONTAL,
    BRST_PAGE_TRANSITION_BLINDS_VERTICAL,
    BRST_PAGE_TRANSITION_DISSOLVE,
    BRST_PAGE_TRANSITION_GLITTER_RIGHT,
    BRST_PAGE_TRANSITION_GLITTER_DOWN,
    BRST_PAGE_TRANSITION_GLITTER_TOP_LEFT_TO_BOTTOM_RIGHT,
    BRST_PAGE_TRANSITION_REPLACE,
    BRST_PAGE_TRANSITION_EOF
} BRST_TransitionStyle;

/*----------------------------------------------------------------------------*/

typedef enum _BRST_PageBoundary {
    BRST_PAGE_MEDIABOX = 0,
    BRST_PAGE_CROPBOX,
    BRST_PAGE_BLEEDBOX,
    BRST_PAGE_TRIMBOX,
    BRST_PAGE_ARTBOX
} BRST_PageBoundary;

/*----------------------------------------------------------------------------*/

/**
  \brief Page orientation
*/
typedef enum _BRST_PageOrientation {
    /// Portrait orientation (longest size vertical)
    BRST_PAGE_ORIENTATION_PORTRAIT = 0,
    /// Landscape orientation (longest size horizontal)
    BRST_PAGE_ORIENTATION_LANDSCAPE
} BRST_PageOrientation;


#endif /* BRST_PAGE_H */